name: java maven
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - name: Setup Maven Action
      #   uses: s4u/setup-maven-action@v1.2.1
      #   with:
      #     java-version: 17
      #     maven: 3.5.4

      # - name: Build with Maven
      #   run: mvn clean install -PallModules --update-snapshots package -Drat.numUnapprovedLicenses=200


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -PallModules -Pgithub deploy -Drat.numUnapprovedLicenses=200 -DskipTests
      #   # env:
      #   #   GITHUB_TOKEN: ${{ secrets.GITHUB1_TOKEN }}      

  

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -PallModules -Drat.numUnapprovedLicenses=200 -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB1_TOKEN }} 



      #     server-id: github
      #     server-username: serwol2 # env variable name for username
      #     server-password: ${{ secrets.GITHUB1_TOKEN }}
      #     #check-latest: true
      #     # cache: maven
      # - name: Build with Maven
      #   #run: mvn install -P allModules,quick,mysql -pl openmeetings-util,openmeetings-db,openmeetings-core,openmeetings-install,openmeetings-service,openmeetings-web,openmeetings-server,openmeetings-webservice -Dwicket.configuration=DEVELOPMENT
      #   run: mvn clean install -PallModules -Pgithub deploy -Drat.numUnapprovedLicenses=200 -DskipTests --update-snapshots package
      #   #run: mvn clean install -PallModules -Drat.numUnapprovedLicenses=200 -DskipTests
      #   # env:

        #   GITHUB_USER_REF: ${{ secrets.GIT_USERNAME }}

        #   GITHUB_TOKEN_REF: ${{ secrets.GIT_TOKEN }}  
               # mvn --batch-mode --update-snapshots package
    
    
    
    
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Package
      #     path: /home/runner/work/openmeetings-project/openmeetings-project/openmeetings-service/target/openmeetings-service-6.3.0-SNAPSHOT.jar

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Package1
      #     path: /home/runner/work/    


    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: serwol2 #${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    
    # - name: Build and push docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     # context: .
    #     push: true
    #     tags: ghcr.io/serwol2/app:latest