name: java maven
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -e clean install -P allModules -Drat.numUnapprovedLicenses=200 -Denforcer.skip=true
        # mvn --batch-mode --update-snapshots package
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging     